name: restici_admin
description: "Administrateur de restici-ecommerce"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.1.beta

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  shared_preferences: ^2.5.4
  iconly: ^1.0.1
  dotted_border: ^3.1.0
  image_picker: ^1.2.1
  uuid: ^4.2.2
  intl: ^0.20.2
  responsive_builder: ^0.7.1
  fl_chart: ^1.1.1
  file_picker: ^10.3.6
  url_launcher: ^6.3.2
  stylish_dialog: ^1.0.2
  shimmer: ^3.0.0
  google_fonts: ^6.3.3
  gap: ^3.0.1
  dio: ^5.9.0
  talker_dio_logger: ^5.1.6
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  encrypt: ^5.0.3
  talker_flutter: ^5.1.6
  internet_connection_checker_plus: ^2.9.1+1
  talker_bloc_logger: ^5.1.6
  fluttertoast: ^9.0.0
  easy_localization: ^3.0.8
  safe_device: ^1.3.8
  html: ^0.15.6
  get_it: ^9.2.0
  flutter_spinkit: ^5.2.2
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.1
  flutter_svg: ^2.2.3
  sidebar_with_animation: ^0.0.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
